# OSCILLATIONS AND ACCURACY OF LINEARIZATION

In [1]:
import matplotlib.pyplot as plt  # type: ignore
import numpy as np  # type: ignore
import os
import pandas as pd  # type: ignore
from typing import Optional, cast, List, Union

import src.constants as cn
from src.score import Score
from src.system_discovery import SystemDiscovery
from src.piecewise_system_discovery import PiecewiseSystemDiscovery
from src.model import Model
from src.timecourse import Timecourse
from src.timecourse_iterator import TimecourseIterator
from src.system_discovery_changepoint_detector import SystemDiscoveryChangepointDetector

# Selecting Oscillating Models and Species

In [2]:
PATH = os.path.join(cn.DATA_DIR, f"find_oscillating_models.csv")
oscillation_df = pd.read_csv(PATH)
oscillation_df

,system_id,species_name,frequencies,endtime
0,BIOMD0000000005,C2,[0.02997],100.0
1,BIOMD0000000005,CP,[0.02997],100.0
2,BIOMD0000000005,M,"[0.02997, 0.05994, 0.10989, 0.13986]",100.0
3,BIOMD0000000005,pM,[0.02997],100.0
4,BIOMD0000000005,Y,[0.02997],100.0
...,...,...,...,...
1107209,BIOMD0000001059,sursmac,[],7000.0
1107210,BIOMD0000001059,smacmit,[],7000.0
1107211,BIOMD0000001059,smac,[],7000.0
1107212,BIOMD0000001060,x1,[],40.0
1107213,BIOMD0000001060,x2,[],40.0

In [6]:
oscillation_df [oscillation_df[cn.COL_FREQUENCIES] == "[]"]

,system_id,species_name,frequencies,endtime
0,BIOMD0000000005,C2,[0.02997],100.0
1,BIOMD0000000005,CP,[0.02997],100.0
2,BIOMD0000000005,M,"[0.02997, 0.05994, 0.10989, 0.13986]",100.0
3,BIOMD0000000005,pM,[0.02997],100.0
4,BIOMD0000000005,Y,[0.02997],100.0
...,...,...,...,...
1107197,BIOMD0000001058,Polo,[0.00999],200.0
1107198,BIOMD0000001058,Sic1t,"[0.00999, 0.01998]",200.0
1107199,BIOMD0000001058,SBF,[0.00999],200.0
1107200,BIOMD0000001058,Cdh1,"[0.00999, 0.01998]",200.0
1107201,BIOMD0000001058,Cdc14,"[0.00999, 0.01998]",200.0